source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '16.2'
use_frameworks! :linkage => :static
inhibit_all_warnings!
use_modular_headers!

install! 'cocoapods',
:generate_multiple_pod_projects => true,
:incremental_installation => true

target 'InstagramCloneApp' do
  pod 'IGHome', :path => 'Modules/IGHome'
  pod 'IGProfile', :path => 'Modules/IGProfile'
end
